export const LOAD_WORKFLOW_COLLECTIONS_HISTORICAL_ENGAGEMENTS = {
  ACTION: 'workflowHistory/LOAD_WORKFLOW_COLLECTIONS_HISTORICAL_ENGAGEMENTS',
  FAILURE:
    'workflowHistory/LOAD_WORKFLOW_COLLECTIONS_HISTORICAL_ENGAGEMENTS_FAILURE',
  SUCCESS:
    'workflowHistory/LOAD_WORKFLOW_COLLECTIONS_HISTORICAL_ENGAGEMENTS_SUCCESS',
};

export const LOAD_WORKFLOW_COLLECTION_HISTORICAL_ENGAGEMENTS = {
  ACTION: 'workflowHistory/LOAD_WORKFLOW_COLLECTION_HISTORICAL_ENGAGEMENTS',
  FAILURE:
    'workflowHistory/LOAD_WORKFLOW_COLLECTION_HISTORICAL_ENGAGEMENTS_FAILURE',
  SUCCESS:
    'workflowHistory/LOAD_WORKFLOW_COLLECTION_HISTORICAL_ENGAGEMENTS_SUCCESS',
};

export const LOAD_WORKFLOW_COLLECTION_DETAIL_FOR_ENGAGEMENT_HISTORY = {
  ACTION:
    'workflowHistory/LOAD_WORKFLOW_COLLECTION_DETAIL_FOR_ENGAGEMENT_HISTORY',
  FAILURE:
    'workflowHistory/LOAD_WORKFLOW_COLLECTION_DETAIL_FOR_ENGAGEMENT_HISTORY_FAILURE',
  SUCCESS:
    'workflowHistory/LOAD_WORKFLOW_COLLECTION_DETAIL_FOR_ENGAGEMENT_HISTORY_SUCCESS',
};

export const REQUEST_COLLECTION_HISTORY_PDF_EMAIL = {
  ACTION: 'workflowHistory/REQUEST_COLLECTION_HISTORY_PDF_EMAIL',
  FAILURE: 'workflowHistory/REQUEST_COLLECTION_HISTORY_PDF_EMAIL_FAILURE',
  SUCCESS: 'workflowHistory/REQUEST_COLLECTION_HISTORY_PDF_EMAIL_SUCCESS',
};

export const RESET_REQUEST_COLLECTION_HISTORY_PDF_EMAIL =
  'workflowHistory/RESET_REQUEST_COLLECTION_HISTORY_PDF_EMAIL';

export const RESET_WORKFLOW_HISTORY = 'workflowHistory/RESET';
export const CLEAR_WORKFLOW_HISTORY_FOR_ALL_COLLECTIONS =
  'workflowHistory/CLEAR_WORKFLOW_HISTORY_FOR_ALL_COLLECTIONS';
export const CLEAR_WORKFLOW_HISTORY_FOR_SINGLE_COLLECTION =
  'workflowHistory/CLEAR_WORKFLOW_HISTORY_FOR_SINGLE_COLLECTION';
export const CLEAR_WORKFLOW_HISTORY_ERROR = 'workflowHistory/CLEAR_ERROR';
