export const CREATE_WORKFLOW_COLLECTION_SUBSCRIPTION = {
  ACTION: 'workflows/CREATE_WORKFLOW_COLLECTION_SUBSCRIPTION',
  FAILURE: 'workflows/CREATE_WORKFLOW_COLLECTION_SUBSCRIPTION_FAILURE',
  SUCCESS: 'workflows/CREATE_WORKFLOW_COLLECTION_SUBSCRIPTION_SUCCESS',
};

export const LOAD_WORKFLOW_COLLECTION_SUBSCRIPTIONS = {
  ACTION: 'workflows/LOAD_WORKFLOW_COLLECTION_SUBSCRIPTIONS',
  FAILURE: 'workflows/LOAD_WORKFLOW_COLLECTION_SUBSCRIPTIONS_FAILURE',
  SUCCESS: 'workflows/LOAD_WORKFLOW_COLLECTION_SUBSCRIPTIONS_SUCCESS',
};

export const UPDATE_WORKFLOW_COLLECTION_SUBSCRIPTION = {
  ACTION: 'workflows/UPDATE_WORKFLOW_COLLECTION_SUBSCRIPTION',
  FAILURE: 'workflows/UPDATE_WORKFLOW_COLLECTION_SUBSCRIPTION_FAILURE',
  SUCCESS: 'workflows/UPDATE_WORKFLOW_COLLECTION_SUBSCRIPTION_SUCCESS',
};
