export const CREATE_WORKFLOW_COLLECTION_ENGAGEMENT_DETAIL = {
  ACTION: 'workflows/CREATE_WORKFLOW_COLLECTION_ENGAGEMENT_DETAIL',
  FAILURE: 'workflows/CREATE_WORKFLOW_COLLECTION_ENGAGEMENT_DETAIL_FAILURE',
  SUCCESS: 'workflows/CREATE_WORKFLOW_COLLECTION_ENGAGEMENT_DETAIL_SUCCESS',
};

export const UPDATE_WORKFLOW_COLLECTION_ENGAGEMENT_DETAIL = {
  ACTION: 'workflows/UPDATE_WORKFLOW_COLLECTION_ENGAGEMENT_DETAIL',
  FAILURE: 'workflows/UPDATE_WORKFLOW_COLLECTION_ENGAGEMENT_DETAIL_FAILURE',
  SUCCESS: 'workflows/UPDATE_WORKFLOW_COLLECTION_ENGAGEMENT_DETAIL_SUCCESS',
};
