/**
 * Definition of Action Types for Wellbeing Dimension Data
 */

export const LOAD_WELLBEING_PROFILE_DATA = {
  ACTION: 'cup/LOAD_WELLBEING_PROFILE_DATA',
  FAILURE: 'cup/LOAD_WELLBEING_PROFILE_DATA_FAILURE',
  SUCCESS: 'cup/LOAD_WELLBEING_PROFILE_DATA_SUCCESS'
};

export const LOAD_WELLBEING_INSIGHTS_DATA = {
  ACTION: 'cup/LOAD_WELLBEING_INSIGHTS_DATA',
  FAILURE: 'cup/LOAD_WELLBEING_INSIGHTS_DATA_FAILURE',
  SUCCESS: 'cup/LOAD_WELLBEING_INSIGHTS_DATA_SUCCESS'
};

export const REQUEST_WELLBEING_RESULTS_PDF_EMAIL = {
  ACTION: 'cup/REQUEST_WELLBEING_RESULTS_PDF_EMAIL',
  FAILURE: 'cup/REQUEST_WELLBEING_RESULTS_PDF_EMAIL_FAILURE',
  SUCCESS: 'cup/REQUEST_WELLBEING_RESULTS_PDF_EMAIL_SUCCESS'
};

export const CLEAR_ERROR = 'cup/CLEAR_ERROR';
export const RESET_REQUEST_WELLBEING_RESULTS_PDF_EMAIL = 'cup/RESET_REQUEST_WELLBEING_RESULTS_PDF_EMAIL'
export const RESET = 'cup/RESET';
