export const LOAD_WORKFLOW_COLLECTION_ENGAGEMENTS = {
  ACTION: 'workflows/LOAD_WORKFLOW_COLLECTION_ENGAGEMENTS',
  FAILURE: 'workflows/LOAD_WORKFLOW_COLLECTION_ENGAGEMENTS_FAILURE',
  SUCCESS: 'workflows/LOAD_WORKFLOW_COLLECTION_ENGAGEMENTS_SUCCESS',
};

export const LOAD_WORKFLOW_COLLECTION_ENGAGEMENT = {
  ACTION: 'workflows/LOAD_WORKFLOW_COLLECTION_ENGAGEMENT',
  FAILURE: 'workflows/LOAD_WORKFLOW_COLLECTION_ENGAGEMENT_FAILURE',
  SUCCESS: 'workflows/LOAD_WORKFLOW_COLLECTION_ENGAGEMENT_SUCCESS',
};

export const CLEAR_WORKFLOW_COLLECTION_ENGAGEMENTS =
  'workflows/CLEAR_WORKFLOW_COLLECTION_ENGAGEMENTS';

export const CREATE_WORKFLOW_COLLECTION_ENGAGEMENT = {
  ACTION: 'workflows/CREATE_WORKFLOW_COLLECTION_ENGAGEMENT',
  FAILURE: 'workflows/CREATE_WORKFLOW_COLLECTION_ENGAGEMENT_FAILURE',
  SUCCESS: 'workflows/CREATE_WORKFLOW_COLLECTION_ENGAGEMENT_SUCCESS',
};

export const RETRIEVE_WORKFLOW_COLLECTION_ENGAGEMENT = {
  ACTION: 'workflows/RETRIEVE_WORKFLOW_COLLECTION_ENGAGEMENT',
  FAILURE: 'workflows/RETRIEVE_WORKFLOW_COLLECTION_ENGAGEMENT_FAILURE',
  SUCCESS: 'workflows/RETRIEVE_WORKFLOW_COLLECTION_ENGAGEMENT_SUCCESS',
};

export const CLEAR_WORKFLOW_COLLECTION_ENGAGEMENT =
  'workflows/CLEAR_WORKFLOW_COLLECTION_ENGAGEMENT';

export const UPDATE_WORKFLOW_COLLECTION_ENGAGEMENT = {
  ACTION: 'workflows/UPDATE_WORKFLOW_COLLECTION_ENGAGEMENT',
  FAILURE: 'workflows/UPDATE_WORKFLOW_COLLECTION_ENGAGEMENT_FAILURE',
  SUCCESS: 'workflows/UPDATE_WORKFLOW_COLLECTION_ENGAGEMENT_SUCCESS',
};
