export const LOAD_WORKFLOW_COLLECTION_RECOMMENDATIONS = {
  ACTION: 'workflows/LOAD_WORKFLOW_COLLECTION_RECOMMENDATIONS',
  FAILURE: 'workflows/LOAD_WORKFLOW_COLLECTION_RECOMMENDATIONS_FAILURE',
  SUCCESS: 'workflows/LOAD_WORKFLOW_COLLECTION_RECOMMENDATIONS_SUCCESS',
};

export const CREATE_WORKFLOW_COLLECTION_RECOMMENDATION = {
  ACTION: 'workflows/CREATE_WORKFLOW_COLLECTION_RECOMMENDATION',
  FAILURE: 'workflows/CREATE_WORKFLOW_COLLECTION_RECOMMENDATION_FAILURE',
  SUCCESS: 'workflows/CREATE_WORKFLOW_COLLECTION_RECOMMENDATION_SUCCESS',
};

export const UPDATE_WORKFLOW_COLLECTION_RECOMMENDATION = {
  ACTION: 'workflows/UPDATE_WORKFLOW_COLLECTION_RECOMMENDATION',
  FAILURE: 'workflows/UPDATE_WORKFLOW_COLLECTION_RECOMMENDATION_FAILURE',
  SUCCESS: 'workflows/UPDATE_WORKFLOW_COLLECTION_RECOMMENDATION_SUCCESS',
};
