export const LOAD_WORKFLOW_COLLECTION_ASSIGNMENTS = {
  ACTION: 'workflows/LOAD_WORKFLOW_COLLECTION_ASSIGNMENTS',
  FAILURE: 'workflows/LOAD_WORKFLOW_COLLECTION_ASSIGNMENTS_FAILURE',
  SUCCESS: 'workflows/LOAD_WORKFLOW_COLLECTION_ASSIGNMENTS_SUCCESS',
};

export const UPDATE_WORKFLOW_COLLECTION_ASSIGNMENT = {
  ACTION: 'workflows/UPDATE_WORKFLOW_COLLECTION_ASSIGNMENT',
  FAILURE: 'workflows/UPDATE_WORKFLOW_COLLECTION_ASSIGNMENT_FAILURE',
  SUCCESS: 'workflows/UPDATE_WORKFLOW_COLLECTION_ASSIGNMENT_SUCCESS',
};
