export const LOAD_WORKFLOW_COLLECTIONS = {
  ACTION: 'workflows/LOAD_WORKFLOW_COLLECTIONS',
  FAILURE: 'workflows/LOAD_WORKFLOW_COLLECTIONS_FAILURE',
  SUCCESS: 'workflows/LOAD_WORKFLOW_COLLECTIONS_SUCCESS',
};

export const LOAD_WORKFLOW_COLLECTION = {
  ACTION: 'workflows/LOAD_WORKFLOW_COLLECTION',
  FAILURE: 'workflows/LOAD_WORKFLOW_COLLECTION_FAILURE',
  SUCCESS: 'workflows/LOAD_WORKFLOW_COLLECTION_SUCCESS',
};

export const UNLOAD_WORKFLOW_COLLECTION =
  'workflows/UNLOAD_WORKFLOW_COLLECTION';

export const SET_CURRENT_WORKFLOW_COLLECTION_URL =
  'workflows/SET_CURRENT_WORKFLOW_COLLECTION_URL';
export const CLEAR_CURRENT_WORKFLOW_COLLECTION_URL =
  'workflows/CLEAR_CURRENT_WORKFLOW_COLLECTION_URL';
